- name: "feat"
  color: "a2eeef"
- name: "chore"
  color: "666666"
- name: "bug"
  color: "d73a4a"
- name: "fix"
  color: "DD7E87"
- name: "ci"
  color: "000000"
- name: "docs"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "build"
  color: "000000"
- name: "perf"
  color: "80BCBD"

- name: "refactor"
  color: "FFB17A"
- name: "revert"
  color: "4F4789"
- name: "wontfix"
  color: "201335"
  description: "This will not be worked on"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "storybook"
  color: "ff4685"
- name: "UI"
  color: "007efd"
- name: "ts-type"
  color: "2f74c0"
- name: "style"
  color: "2962ea"
- name: "test"
  color: "fb4443"
- name: "repo"
  color: "ededed"


